AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Document Extraction

  SAM Template for Nucleon

Globals:
  Function:
    Runtime: python3.11
    Handler: main.lambda_handler
    Architectures:
      - arm64
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: INFO

Resources:    
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'*'"

  NucleonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Nucleon/
      Timeout: 480
      MemorySize: 2048
      Policies:
        - Statement:
            - Sid: "FullAccessToS3Bucket"
              Effect: "Allow"
              Action:
                - "s3:*"
              Resource:
                - "arn:aws:s3:::nucleon-test-bucket"
                - "arn:aws:s3:::nucleon-test-bucket/*"
        - Statement:
            - Sid: "BedrockScopedAccess"
              Effect: "Allow"
              Action:
                - "bedrock:InvokeModel"
              Resource:
                - "arn:aws:bedrock:*::foundation-model/*"
        - Statement:
            - Sid: "FullAccessToTextract"
              Effect: "Allow"
              Action:
                - "textract:*"
              Resource: "*"
        - Statement:
            - Sid: "SSMAccess"
              Effect: "Allow"
              Action:
                - "ssm:GetParameter"
                - "ssm:GetParameters"
                - "ssm:GetParametersByPath" # Add other SSM actions as needed
                - "ssm:PutParameter"
              Resource: "*"
      Environment:
        Variables:
          FOLDER_PATH: "final-testing/final-testing/Banyan-Hospital/SUNIL-JOHARY"
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /Nucleon
            Method: POST
      
  RequestApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Request_api/
      Timeout: 480
      MemorySize: 2048
      Policies:
        - Statement:
            - Sid: "InvokeRequestApiFunction"
              Effect: "Allow"
              Action: "lambda:InvokeFunction"
              Resource: !GetAtt NucleonFunction.Arn
              # NUCLEON_FUNCTION_ARN: !GetAtt NucleonFunction.Arn
        - Statement:
            - Sid: "FullAccessToS3Bucket"
              Effect: "Allow"
              Action:
                - "s3:*"
              Resource:
                - "arn:aws:s3:::nucleon-test-bucket"
                - "arn:aws:s3:::nucleon-test-bucket/*"
                - "arn:aws:s3:::nucleus-demo-jyoti/*"
                - "arn:aws:s3:::nucleus-demo-jyoti/"
        - Statement:
            - Sid: "SSMAccess"
              Effect: "Allow"
              Action:
                - "ssm:GetParameter"
                - "ssm:GetParameters"
                - "ssm:GetParametersByPath" # Add other SSM actions as needed
                - "ssm:PutParameter"
              Resource: "*"
      Environment:
        Variables:
          FOLDER_PATH: "final-testing/final-testing/Banyan-Hospital/SUNIL-JOHARY"
          NUCLEON_FUNCTION_ARN: !GetAtt NucleonFunction.Arn
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /requestapi
            Method: POST

  ResponseApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Response_api/
      Timeout: 480
      MemorySize: 2048
      Policies:
        - Statement:
            - Sid: "SSMAccess"
              Effect: "Allow"
              Action:
                - "ssm:GetParameter"
                - "ssm:GetParameters"
                - "ssm:GetParametersByPath" # Add other SSM actions as needed
                - "ssm:PutParameter"
              Resource: "*"
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /responseapi
            Method: POST
